tasks:
  - name: Install Purescript and Spago 
    command: |
      npm install -g purescript
      npm install -g spago

vscode:
  extensions:
    - nwolverson.ide-purescript
    - nwolverson.language-purescript